FROM holbertonschool/ubuntu-1404-python3
RUN mkdir AuthServices
COPY . /AuthServices
RUN cd AuthServices/ && pip3 install -r requirements.txt --trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host pypi.python.org 
WORKDIR AuthServices
EXPOSE 5000
CMD ["python3", "-m", "Controllers.user_controller"]
