FROM holbertonschool/ubuntu-1404-python3
RUN mkdir AuthServices
COPY . /AuthServices
RUN cd AuthServices/ && pip3.4 install -r requirements.txt
WORKDIR AuthServices
EXPOSE 5000
CMD ["python3", "-m", "Controllers.user_controller"]
