FROM golang
RUN mkdir RecoEngineWorkspace
COPY . /RecoEngineWorkspace
RUN cd RecoEngineWorkspace/ &&\
    export GOPATH=$GOPATH:/go/Team-Rocket/RecoEngineWorkspace/ &&\
    go get github.com/gorilla/mux &&\
    go get github.com/samuel/go-zookeeper/zk &&\
    cd src/RecommendationEngine/ &&\
    go build &&\
    cd ../../ &&\
    cp -r src /go/
EXPOSE 8001
CMD ["go", "run", "RecommendationEngine"]
