FROM n0485/recoengine:latest
RUN rm -rf RecoEngineWorkspace
RUN mkdir RecoEngineWorkspace
COPY . RecoEngineWorkspace/
RUN cd RecoEngineWorkspace/ &&\
    export GOPATH=$GOPATH:/go/RecoEngineWorkspace/ &&\
    cd src/RecommendationEngine/ &&\
    go build &&\
    cd ../../ &&\
    cp -r src /go/
EXPOSE 8001
CMD ["go", "run", "RecommendationEngine"]
